export default {
  FULLDATE: "Marca temporal",
  CONSENTIMIENTO: " Por todo ello, DOY MI CONSENTIMIENTO:",
  DNI: "DNI o Pasaporte",
  TAG: "TAG",
  CENTER: "Center",
  INDICADOR_1A: "Indicador 1: Realiza las tareas que le son asignadas dentro del grupo en los plazos requeridos.",
  INDICADOR_2A: "Indicador 2: Participa de forma activa en los espacios de encuentro del equipo, compartiendo la información, los conocimientos y las experiencias",
  INDICADOR_3A: "Indicador 3: Colabora en la definición, la organización y distribución de las tareas de grupo.",
  MAYOR_POS_MEJORA_INDICADOR_A: "Señala el indicador sobre el que percibes mayor posibilidad de mejora: ",
  PLAN_MEJOR_INDICADOR_A: "Señala un plan de mejora para avanzar en el indicador en el que percibas una mayor debilidad: ",
  INDICADOR_1B: "Indicador 1: Transmito información relevante.",
  INDICADOR_2B: "Indicador 2: Las presentaciones están estructuradas, cumpliendo con los requisitos exigidos, si los hubiera.",
  INDICADOR_3B: "Indicador 3: En mis presentaciones utilizo medios de apoyo.",
  MAYOR_POS_MEJORA_INDICADOR_B: "Señala el indicador sobre el que percibes mayor posibilidad de mejora: 2",
  PLAN_MEJOR_INDICADOR_B: "Señala un plan de mejora para avanzar en el indicador en el que percibas una mayor debilidad: 3",
  ACTIVIDADES_UTILES: "En general, las actividades previstas del curso son útiles.",
  CAPACIDAD_REALIZACION: "Confío en mi capacidad de realizar exitosamente las actividades establecidas.",
  METODOS_ENSENANZA: "Los métodos de enseñanza descritos me involucran (enganchan) activamente en el curso.",
  DISFRUTAR_ACTIVIDAD: "Creo que voy a disfrutar de las actividades del curso.",
  CAPACIDAD_CALIFICACION: "Me considero capaz de obtener una alta calificación en la actividad.",
  CONTROL_APRENDIZAJE: "Tengo control sobre cómo aprendo los contenidos del curso/actividad.",
  PREOCUPACION_PROFESOR: "El/la profesor/a se preocupa por mi desempeño en el curso.",
  CONOCIMIENTO_FUTURO: "Considero que los conocimientos adquiridos en este curso son importantes para mi futuro.",
  PROFESOR_AMIGABLE: "El/La profesor/a es amigable/comprensible."
};
